# Generated by Django 5.0 on 2024-01-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_rename_iduser_admin_user_rename_iduser_doctor_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialty',
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='cv',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='scheduledTherapySessions',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='anxietyScore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='patient',
            name='averageHoursOfGammingPerMounth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='averageHoursOfGammingPerWeek',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='depressionScore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='patient',
            name='excessiveSleepinessScore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insomniaScore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='patient',
            name='levelOfAddiction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
