# Generated by Django 5.0 on 2024-01-07 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_remove_doctor_specialty_user_country_alter_doctor_cv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
    ]
